version: '3'

services:

  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - '5532:5532'
    volumes:
      - ./dumps:/code/dumps
      - ./data/postgresql:/var/lib/postgresql/data

  redis:
     image: redis:alpine
     ports:
        - '6379:6379'
