# Generated by Django 3.2.7 on 2021-10-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_request', models.DateField(auto_now=True, verbose_name='Last request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
