# Generated by Django 3.2.7 on 2021-10-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='last_request',
            field=models.DateTimeField(auto_now=True, verbose_name='Last request'),
        ),
    ]
